import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowRight,Check,ChevronDown,ExternalLink,Menu,ShieldCheck,BookOpen,Server,Smartphone,Monitor,Apple,HelpCircle} from 'lucide-react';
import './styles.css';

const AFF='https://justmysocks.net/members/aff.php?aff=25290';
const plans=[
 {name:'LA500',tag:'入门首选',price:'$5.88',period:'/ 月',traffic:'500 GB / 月',speed:'最高 2.5 Gbps',locations:'洛杉矶',audience:'轻度使用、日常浏览、远程办公',accent:'blue'},
 {name:'LA1000',tag:'更充裕的选择',price:'$9.88',period:'/ 月',traffic:'1,000 GB / 月',speed:'最高 2.5 Gbps',locations:'洛杉矶',audience:'多设备、高清流媒体、家庭用户',accent:'violet'},
 {name:'LA2000',tag:'重度用户',price:'$19.88',period:'/ 月',traffic:'2,000 GB / 月',speed:'最高 2.5 Gbps',locations:'洛杉矶',audience:'大流量、团队或多终端使用',accent:'orange'}
];
const faqs=[['Just My Socks 是什么？','Just My Socks 是一个面向中文用户的网络服务品牌。本网站是独立的第三方教程站，负责整理公开信息、购买步骤和设备配置方法。'],['LA500 和 LA1000 怎么选？','如果主要是网页、邮件和轻量工作，LA500 通常足够；如果你有多台设备、高清视频或更高流量需求，可以考虑 LA1000。建议按实际用量选择。'],['如何续费或取消？','登录官方账户后台查看订阅状态与账单设置。具体规则、续费价格和退款政策可能变化，请以官方页面当时显示的条款为准。'],['推广链接会让我多付钱吗？','不会。通过本页推广链接进入官方页面不会增加你的支付金额；如果最终购买成功，网站运营者可能获得佣金。'],['价格和套餐会变化吗？','会。本文的价格仅用于帮助理解套餐差异，最终价格、库存和可用地区请以官方结算页面为准。']];

function Button({children,href=AFF,secondary=false}){return <a className={'btn '+(secondary?'btn-secondary':'')} href={href} target="_blank" rel="noreferrer">{children}<ArrowRight size={16}/></a>}
function Header(){const [open,setOpen]=useState(false);return <header className="header"><div className="nav wrap"><a className="logo" href="#top"><span className="logo-mark">J</span><span>Just My Socks<span className="logo-sub">中文指南</span></span></a><button className="menu" onClick={()=>setOpen(!open)} aria-label="打开菜单"><Menu/></button><nav className={open?'nav-links open':'nav-links'}><a href="#plans" onClick={()=>setOpen(false)}>套餐比较</a><a href="#buy" onClick={()=>setOpen(false)}>购买教程</a><a href="#setup" onClick={()=>setOpen(false)}>设备配置</a><a href="#faq" onClick={()=>setOpen(false)}>常见问题</a><Button>前往官方页面</Button></nav></div></header>}
function Hero(){return <section className="hero" id="top"><div className="hero-grid wrap"><div className="hero-copy"><div className="eyebrow"><span className="dot"/>独立第三方中文教程</div><h1>把套餐看懂，<br/><em>把配置做好。</em></h1><p className="lead">从 LA500、LA1000 的差异，到不同设备的上手步骤。用一份清晰、克制的指南，帮你做出适合自己的选择。</p><div className="hero-actions"><Button>查看官方套餐</Button><a className="text-link" href="#plans">先比较套餐 <ArrowRight size={16}/></a></div><div className="trust"><ShieldCheck size={17}/><span>信息持续整理 · 价格以官方页面为准</span></div></div><div className="hero-card"><div className="card-top"><span>快速开始</span><span className="status"><i/>可用</span></div><div className="route"><div className="route-node"><span className="route-icon"><BookOpen/></span><b>了解套餐</b><small>先看差异</small></div><div className="route-line"/><div className="route-node"><span className="route-icon"><Server/></span><b>完成购买</b><small>官方页面</small></div><div className="route-line"/><div className="route-node"><span className="route-icon"><Check/></span><b>开始配置</b><small>按设备操作</small></div></div><div className="card-note">适合第一次了解 Just My Socks 的中文用户</div></div></div></section>}
function PlanCard({p}){return <article className={'plan-card '+p.accent}><div className="plan-head"><span className="plan-name">{p.name}</span><span className="tag">{p.tag}</span></div><div className="price">{p.price}<small>{p.period}</small></div><div className="plan-rule"/><ul><li><Check size={16}/>{p.traffic}</li><li><Check size={16}/>{p.speed}</li><li><Check size={16}/>{p.locations} 线路</li></ul><p className="audience">适合：{p.audience}</p><a href="#buy" className="plan-link">查看购买步骤 <ArrowRight size={15}/></a></article>}
function Plans(){return <section className="section plans" id="plans"><div className="wrap"><div className="section-head"><div><span className="kicker">PLANS / 套餐比较</span><h2>先找到合适的<br/><span>使用尺度。</span></h2></div><p>套餐名称、价格和资源可能调整。这里提供结构化的快速对比，最终请以官方页面为准。</p></div><div className="plan-grid">{plans.map(p=><PlanCard key={p.name} p={p}/>)}</div><div className="compare-note"><span>不确定选哪一个？</span>从 LA500 开始，按实际用量观察，再决定是否升级。<a href="#faq">查看选择建议 <ArrowRight size={14}/></a></div></div></section>}
function GuideStep({num,title,children}){return <div className="step"><div className="step-num">{num}</div><div><h3>{title}</h3><p>{children}</p></div></div>}
function BuySetup(){return <section className="section dark-section" id="buy"><div className="wrap split"><div><span className="kicker light">BUYING GUIDE / 购买教程</span><h2>三步完成购买，<br/><span>信息透明。</span></h2><p className="dark-lead">本教程仅用于说明流程。点击按钮后会打开 Just My Socks 官方页面，请在官方页面核对最新价格与条款。</p><Button>打开推广链接</Button></div><div className="steps"><GuideStep num="01" title="打开官方页面">通过本页按钮进入官方站点，在注册页面创建账户。</GuideStep><GuideStep num="02" title="选择套餐并付款">结合用量选择套餐，确认账单周期、支付方式与服务条款。</GuideStep><GuideStep num="03" title="查收账户信息">付款完成后，在账户后台查看服务信息，再根据设备教程完成配置。</GuideStep></div></div></section>}
const devices=[['Windows','Windows 10 / 11','使用系统网络设置或兼容客户端导入账户信息。',<Monitor/>],['macOS','macOS 12+','在系统设置中添加网络服务，按官方参数完成连接。',<Apple/>],['iPhone / iPad','iOS / iPadOS','使用兼容的客户端应用，复制账户信息后导入配置。',<Smartphone/>],['Android','Android 10+','从可信来源安装客户端，授权后导入订阅或服务器信息。',<Smartphone/>]];
function Setup(){return <section className="section setup" id="setup"><div className="wrap"><div className="section-head"><div><span className="kicker">SETUP / 设备配置</span><h2>按设备查看<br/><span>上手路径。</span></h2></div><p>每台设备的菜单名称可能不同。教程会持续补充截图和更详细的排障说明。</p></div><div className="device-grid">{devices.map(([title,sub,desc,icon])=><article className="device-card" key={title}><div className="device-icon">{icon}</div><div><h3>{title}</h3><span>{sub}</span><p>{desc}</p><a href="#faq">查看配置要点 <ArrowRight size={15}/></a></div></article>)}</div></div></section>}
function FAQ(){const [active,setActive]=useState(0);return <section className="section faq" id="faq"><div className="wrap faq-grid"><div><span className="kicker">FAQ / 常见问题</span><h2>先把疑问<br/><span>问清楚。</span></h2><p>如果你没有找到答案，可以先回到官方页面核对最新信息。</p><a className="text-link" href={AFF} target="_blank" rel="noreferrer">访问官方帮助中心 <ExternalLink size={15}/></a></div><div className="accordion">{faqs.map(([q,a],i)=><div className={'faq-item '+(active===i?'active':'')} key={q}><button onClick={()=>setActive(active===i?-1:i)}><span>{q}</span><ChevronDown size={18}/></button>{active===i&&<p>{a}</p>}</div>)}</div></div></section>}
function Disclosure(){return <section className="disclosure"><div className="wrap disclosure-inner"><div className="disclosure-icon"><HelpCircle/></div><div><h3>推广披露</h3><p>本站是独立的第三方教程网站，不代表 Just My Socks 官方。部分按钮和链接可能是推广链接；如果你通过这些链接完成购买，网站运营者可能获得佣金，但你的支付金额不会因此增加。</p></div><a href="#top" aria-label="回到顶部">↑</a></div></section>}
function Footer(){return <footer><div className="wrap footer-grid"><div><a className="logo footer-logo" href="#top"><span className="logo-mark">J</span><span>Just My Socks<span className="logo-sub">中文指南</span></span></a><p>一份面向中文用户的独立教程与配置指南。</p></div><div className="footer-links"><a href="#plans">套餐比较</a><a href="#buy">购买教程</a><a href="#setup">设备配置</a><a href="#faq">常见问题</a></div><div className="footer-right"><span>© 2026 JMS Guide</span><a href={AFF} target="_blank" rel="noreferrer">官方页面 <ExternalLink size={13}/></a></div></div></footer>}
function App(){return <><Header/><main><Hero/><Plans/><BuySetup/><Setup/><FAQ/><Disclosure/></main><Footer/></>};
createRoot(document.getElementById('root')).render(<App/>);
